doctor/urls.py
from django.conf.urls import url
from doctor import views

app_name = 'doctor'

urlpatterns = [
    url(r'^list/$', views.ListDoctors.as_view(template_name='doctor/list_doctors.html'), name='list_doctors'),
    url(r'^(?P<pk>\d+)/$', views.DoctorDetails.as_view(template_name='doctor/doctor_details.html'), name='doctor_details'),
    url(r'^list/first-level/$', views.ListFirstLevelDoctors.as_view(template_name='doctor/list_first_doctors.html'), name='list_first_doctors'),
    url(r'^list/second-level/$', views.ListSecondLevelDoctors.as_view(template_name='doctor/list_second_doctors.html'), name='list_second_doctors'),
    url(r'^register/(?P<pk>\d+)/$', views.RegisterView.as_view(template_name='doctor/register.html'), name='register'),
]

ligonine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ligonine import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('registration.urls', namespace='registration')),
    url(r'^doctors/', include('doctor.urls', namespace='doctor')),
    url(r'^reset/', include('password_reset.urls')),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views # default login signout views from django
from . import views
from django.contrib.auth.views import (
    password_change,
)

app_name = 'registration'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^(?P<pk>\d+)/my-registrations/$', views.ListUsersRegistrations.as_view(template_name='registration/registration_list.html'), name='registrations'),
    url(r'^(?P<pk>\d+)/remove/$', views.RegistrationDeleteView.as_view(template_name='registration/registration_remove.html'), name='registration_remove'),
    url(r'^password/change/$', password_change, {'template_name': 'registration/password_change.html','post_change_redirect': 'registration:login'}, name='password_change'),
]

doctor/models.py
from django.db import models
# Create your models here.
from registration.models import MyUser
class Doctor(models.Model):
    name = models.CharField(max_length=140, unique=True)
    specialist = models.CharField(max_length=50)
    section = models.CharField(max_length=100)
    cabinet = models.IntegerField()
    email = models.EmailField(max_length=60)
    telephone_number = models.CharField(max_length=50)
    level = models.CharField(max_length=10)
    monday = models.CharField(max_length=20, null=True)
    tuesday = models.CharField(max_length=20, null=True)
    wednesday = models.CharField(max_length=20, null=True)
    thursday = models.CharField(max_length=20, null=True)
    friday = models.CharField(max_length=20, null=True)
    saturday = models.CharField(max_length=10, null=True)
    sunday = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.name


class PacientRegister(models.Model):
    doctor = models.ForeignKey(Doctor, related_name='register')
    user = models.ForeignKey(MyUser, related_name='register')
    date = models.CharField(max_length=100, null=True)
    class Meta:
        unique_together = ('doctor', 'date',)

doctor/forms.py
from django import forms
from .models import PacientRegister

class RegisterForm(forms.ModelForm):
  CHOICES = (('00', '00'),('10', '10'),('20', '20'),('30', '30'),('40', '40'),('50', '50'),)
  CHOICES1 = (('07', '07'),('08', '08'),('09', '09'),('10', '10'),('11', '11'),('12', '12'),
             ('13', '13'),('14', '14'),('15', '15'),('16', '16'),('17', '17'),('18', '18'),
             ('19', '19'),)
  minutes = forms.ChoiceField(choices=CHOICES)
  hour = forms.ChoiceField(choices=CHOICES1)
  class Meta:
    model = PacientRegister
    fields = ('date', 'hour', 'minutes',)
    widgets = {
            'date': forms.DateTimeInput(attrs={'id': 'datepicker'}),
        }

doctor/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from doctor.models import Doctor, PacientRegister
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegisterForm
from django.core.urlresolvers import reverse_lazy
from django.db import IntegrityError
from django.http import request
import datetime

# Create your views here.
class RegisterView(LoginRequiredMixin, CreateView):
  model = PacientRegister
  form_class = RegisterForm
  success_url = reverse_lazy('index')

  def form_valid(self, form):
    try:
      self.object = form.save(commit=False)
      doc = Doctor.objects.get(pk=self.kwargs['pk'])
      day = self.request.POST.get('date')
      hour = self.request.POST.get('hour')
      minutes = self.request.POST.get('minutes')
      today = datetime.datetime.today().strftime('%m/%d/%Y')
      # Ar gera diena?
      if(int(day[-4:]) <= int(today[-4:])):
        if(today >= day):
          context = {'form': form, 'errmsg': u'Galite registruotis tik ateinančioms dienoms'}
          return render(self.request, 'doctor/register.html', context)
      week_day = datetime.datetime.strptime(self.request.POST.get('date'), '%m/%d/%Y').strftime('%A').lower()
      if(week_day == 'sunday' or week_day == 'saturday'):
        context = {'form': form, 'errmsg': 'Savaitgaliais daktarai nedirba'}
        return render(self.request, 'doctor/register.html', context)
      # Ar daktaras dirba tom valandom ?
      work_time = doc.__dict__[week_day]
      doc_start_hour = work_time[:2]
      doc_end_hour = work_time[8:10]
      if(doc_start_hour > hour or hour >= doc_end_hour):
        context = {'form': form, 'errmsg': u'Daktaras šiuo metu, šia dieną nedirba.'}
        return render(self.request, 'doctor/register.html', context)
      # Jei viskas gerai:
      self.object.user = self.request.user
      self.object.doctor = doc
      self.object.date = day + ' ' + hour + ':' + minutes
      self.object.save()
      return super(RegisterView, self).form_valid(form)
    except IntegrityError:
      context = {'form': form, 'errmsg': u'Laikas užimtas'}
      return render(self.request, 'doctor/register.html', context)


class ListDoctors(ListView):
  model = Doctor

  def get_queryset(self):
    name = self.request.GET.get('name')
    if (name == None):
      object_list = self.model.objects.all()
    else:
      object_list = self.model.objects.filter(name__icontains=name)
    return object_list


class ListFirstLevelDoctors(LoginRequiredMixin, ListView):
  model = Doctor
  login_url = 'registration:login'

  def get_queryset(self):
    object_list = self.model.objects.filter(level=1)
    return object_list


class ListSecondLevelDoctors(LoginRequiredMixin, ListView):
  model = Doctor
  login_url = 'registration:login'


  def get_queryset(self):
    object_list = self.model.objects.filter(level=2)
    return object_list


class DoctorDetails(DetailView):
  model = Doctor

ligonine/views.py
from django.shortcuts import render

def index(request):

    return render(request, 'index.html')

doctor/templates/doctor/doctor_details.html
{% extends 'base.html' %}
 {% block content %}
  <div class='login'>
    <h2>Gydytojo informacija</h2>
    <div class='doctor'>
    <div class='info'>
      <h4>Vardas, Pavardė: {{doctor.name}} </h4>
      <h4>Daktaro specialybė: {{doctor.specialist}}</h4>
      <h4>Daktaro kabinetas: {{doctor.cabinet}}</h4>
      <h4>Daktaro El.paštas: {{doctor.email}}</h4>
      <h4>Daktaro telefonas: {{doctor.telephone_number}}</h4>
      </div>
      <div class='timetable'>
        <h3>Darbo laikas:</h3>
        <p>Pirmadienis: {{doctor.monday}}</p>
        <p>Antradienis: {{doctor.tuesday}}</p>
        <p>Trečiadienis: {{doctor.wednesday}}</p>
        <p>Ketvirtadienis: {{doctor.thursday}}</p>
        <p>Penktadienis: {{doctor.friday}}</p>
      </div>
    </div>
    <p><a href="{% url 'doctor:list_doctors' %}">Grįžti atgal</a></p>

  </div>
 {% endblock %}}

doctor/templates/doctor/list_doctors.html
{% extends 'base.html' %}
 {% block content %}
<h2 style='text-align: center'>GYDYTOJŲ DARBO GRAFIKAI</h2>

<form action="" method='GET' class='search'>
    {% csrf_token %}
    <input id='searchinput' type="text" name='name' placeholder="Įveskite daktaro vardą..">
    <input class='button' type="submit" value="Ieškoti">
</form>

    <table id='doctor-list'>
      <tr>
        <th>Specialistas</th>
        <th>Skyrius ar filialas</th>
        <th>Kabinetas</th>
        <th>Gydytojas</th>
        <th>Lygis</th>
        <th>Pirmadienis</th>
        <th>Antradienis</th>
        <th>Trečiadienis</th>
        <th>Ketvirtadienis</th>
        <th>Penktadienis</th>
        <th>Šeštadienis</th>
        <th>Sekmadienis</th>
      </tr>
  {% for doctor in doctor_list %}
      <tr>
        <td>{{doctor.specialist}}</td>
        <td>{{doctor.section}}</td>
        <td>{{doctor.cabinet}}</td>
        <td><a href="{% url 'doctor:doctor_details' pk=doctor.pk %}">{{doctor.name}}</a></td>
        <td>{{doctor.level}}</td>
        <td>{{doctor.monday}}</td>
        <td>{{doctor.tuesday}}</td>
        <td>{{doctor.wednesday}}</td>
        <td>{{doctor.thursday}}</td>
        <td>{{doctor.friday}}</td>
        <td>{{doctor.saturday}}</td>
        <td>{{doctor.sunday}}</td>
      </tr>
  {% endfor %}
    </table>
 {% endblock %}

doctor/templates/doctor/list_first_doctors.html
 {% extends 'base.html' %}
 {% block content %}
<h2 style='text-align: center'>GYDYTOJŲ DARBO GRAFIKAI</h2>

    <table id='doctor-list'>
      <tr>
        <th>Specialistas</th>
        <th>Skyrius ar filialas</th>
        <th>Kabinetas</th>
        <th>Gydytojas</th>
        <th>Lygis</th>
        <th>Pirmadienis</th>
        <th>Antradienis</th>
        <th>Trečiadienis</th>
        <th>Ketvirtadienis</th>
        <th>Penktadienis</th>
        <th>Funkcija</th>
      </tr>
  {% for doctor in doctor_list %}
      <tr>
        <td>{{doctor.specialist}}</td>
        <td>{{doctor.section}}</td>
        <td>{{doctor.cabinet}}</td>
        <td><a href="{% url 'doctor:doctor_details' pk=doctor.pk %}">{{doctor.name}}</a></td>
        <td>{{doctor.level}}</td>
        <td>{{doctor.monday}}</td>
        <td>{{doctor.tuesday}}</td>
        <td>{{doctor.wednesday}}</td>
        <td>{{doctor.thursday}}</td>
        <td>{{doctor.friday}}</td>
        <td><a href="{% url 'doctor:register' pk=doctor.pk %}" class='button1'>Registruotis</a></td>
      </tr>
  {% endfor %}
    </table>
 {% endblock %}

doctor/templates/doctor/list_second_doctors.html
 {% extends 'base.html' %}
 {% block content %}
<h2 style='text-align: center'>GYDYTOJŲ DARBO GRAFIKAI</h2>

    <table id='doctor-list'>
      <tr>
        <th>Specialistas</th>
        <th>Skyrius ar filialas</th>
        <th>Kabinetas</th>
        <th>Gydytojas</th>
        <th>Lygis</th>
        <th>Pirmadienis</th>
        <th>Antradienis</th>
        <th>Trečiadienis</th>
        <th>Ketvirtadienis</th>
        <th>Penktadienis</th>
        <th>Funkcija</th>
      </tr>
  {% for doctor in doctor_list %}
      <tr>
        <td>{{doctor.specialist}}</td>
        <td>{{doctor.section}}</td>
        <td>{{doctor.cabinet}}</td>
        <td><a href="{% url 'doctor:doctor_details' pk=doctor.pk %}">{{doctor.name}}</a></td>
        <td>{{doctor.level}}</td>
        <td>{{doctor.monday}}</td>
        <td>{{doctor.tuesday}}</td>
        <td>{{doctor.wednesday}}</td>
        <td>{{doctor.thursday}}</td>
        <td>{{doctor.friday}}</td>
        <td><a href="{% url 'doctor:register' pk=doctor.pk %}" class='button1'>Registruotis</a></td>
      </tr>
  {% endfor %}
    </table>
 {% endblock %}

doctor/templates/doctor/register.html
{% extends 'base.html' %}
 {% block content %}

<div class="login">
  <h3>Pasirinkite datą ir laiką</h3>
  <form class='login-form' method='POST'>
    {% csrf_token %}
    <div class='register'>
      <label for="datepicker">Diena:</label>
      <input type="text" name="date" value="" id="datepicker" maxlength="100" required />
      <label for="id_hour">Valanda:</label>
      {{form.hour}}
      <label for="id_minutes">Minutės:</label>
      {{form.minutes}}
      <input type="submit" value='Išsaugoti' class="button">
      {{ errmsg }}
    </div>
</form>
</div>
 {% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Ligonine</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>

    {{ form.media }}

  </head>
  <body>
    <div class="menu">
      <div class="logo">
        <img src="https://registracija.vrcp.lt/images/title_bar.jpg" alt="">
      </div>
      <div class="link">
        <ul id="horizontal-list">

          <li><a href="{% url 'registration:logout' %}">Išsiregistruoti ir baigti darbą</a> | </li>
          <li><a href="{% url 'doctor:list_doctors' %}">GYDYTOJŲ DARBO GRAFIKAI</a> | </li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'doctor:list_first_doctors' %}">REGISTRACIJA PAS PIRMINIO LYGIO GYDYTOJUS</a> | </li>
          {% else %}
          <li><a href="{% url 'registration:login'%}">REGISTRACIJA PAS PIRMINIO LYGIO GYDYTOJUS</a> | </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li><a href="{% url 'doctor:list_second_doctors' %}">REGISTRACIJA PAS ANTRINIO LYGIO GYDYTOJUS</a></li>
          {% else %}
          <li><a href="{% url 'registration:login'%}">REGISTRACIJA PAS ANTRINIO LYGIO GYDYTOJUS</a></li>
          {% endif %}
          {% if user.is_authenticated %}
          <li> | <a href="{% url 'registration:password_change'%}">PAKEISTI SLAPTAŽODĮ</a> | </li>
          <li><a href="{% url 'registration:registrations' pk=user.pk%}">MANO REGISTRACIJOS</a></li>
          {% endif %}
        </ul>
        <hr>
      </div>

    </div>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
  {% block content %}


<div class="list">
  <div class="first">
    {% if user.is_authenticated %}
      <p><a href="{% url 'doctor:list_first_doctors' %}">
        <strong>REGISTRACIJA PAS SAVO ŠEIMOS GYDYTOJĄ <br>
                ARBA KITUS PIRMINIO LYGIO GYDYTOJUS <br>
                (ODONTOLOGĄ, GINEKOLOGĄ, PSICHOLOGĄ)
        </strong>
      </a></p>
      {% else %}
      <p><a href="{% url 'registration:login' %}">
        <strong>REGISTRACIJA PAS SAVO ŠEIMOS GYDYTOJĄ <br>
                ARBA KITUS PIRMINIO LYGIO GYDYTOJUS <br>
                (ODONTOLOGĄ, GINEKOLOGĄ, PSICHOLOGĄ)
        </strong>
      </a></p>
    {% endif %}
  </div>

  <div class="second">
    {% if user.is_authenticated %}
      <p><a href="{% url 'doctor:list_second_doctors' %}">
        <strong>REGISTRACIJA PAS GYDYTOJUS KONSULTANTUS (ANTRINIS LYGIS)</strong>
      </a></p>
    {% else %}
      <p><a href="{% url 'registration:login' %}">
        <strong>REGISTRACIJA PAS GYDYTOJUS KONSULTANTUS (ANTRINIS LYGIS)</strong>
      </a></p>
    {% endif %}

  </div>
</div>



  {% endblock %}

templates/password_reset/recovery_done.html
{% extends "base.html" %}
  {% block content %}
    <div class="login">
      <h4>Jūsų slaptažodis sėkmingai pakeistas</h4>
      <h5><a href="{%url 'registration:login'%}">Galite prisijungti prie sistemos</a></h5>
    </div>
  {% endblock %}

templates/password_reset/recovery_form.html
{% extends "base.html" %}
  {% block content %}
    <div class="login">
      <form class="reminder"  method="post">
        {% csrf_token %}
        <label for="username_or_email">Įrašykite elektroninį paštą</label>
        {{form.username_or_email}}
        <input type="submit" name="" value="siųsti">
        {% if form.errors %}
        <p>Paštas neteisingas!</p>
        {% endif %}

      </form>
    </div>
  {% endblock %}

templates/password_reset/reset.html
{% extends "base.html" %}
  {% block content %}
    <div class="login">
      <form class="login-form" method="post">
        {% csrf_token %}
        <label for="password1">Naujas slaptažodis</label>
        {{form.password1}} <br>
        <label for="password2">Pakartokite naują slaptažodį</label>
        {{form.password2}} <br>
        <input type="submit" name="" value="Pakeisti slaptažodį">
      </form>
    </div>
  {% endblock %}

templates/password_reset/reset_sent.html
{% extends "base.html" %}
  {% block content %}
    <div class="login">
      <h3>Nuoroda su slaptažodžio priminimu buvo išsiųsta į jūsų paštą!</h3>
    </div>
  {% endblock %}